spring:
  application:
    name: FitnessTracker

  data:
    mongodb:
      uri: 
      database: fitness

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 8080

# Logging
logging:
  level:
    com.abhi.FitnessTracker: DEBUG
    org.springframework.data.mongodb: INFO
